baseURL: https://bszafarz.pl
languageCode: pl-PL
title: bszafarz
theme: hugo-refresh

# This options specify where to look for the images used in this config
# The default value is the "asset" directory of hugo-refresh theme
assetDir: "static"

# Option to specify the default language of the theme
# I.e., the landing language of your root 
DefaultContentLanguage: pl

## Option to disable additional language in your site.
# disableLanguages: ["ru"]

disableKinds: ["sitemap","RSS"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

params:
  # parameter used to specify the number of article in each row 
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 3

  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/avataaars.png"

  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: true
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: true
  # option to specify the main colour of the theme
  mainColour: "#788cc9"

  # summary options
  summary:
    defaultImage : "/images/summary_background.jpg"
  
  # loading options
  loading:
    image: "/images/icons/loaders/spinning-circles.svg"
    
  # main pages options
  mainPage:
    fontFamily: "Atkinson Hyperlegible" 

  # sidebar options
  sidebar:
    logo: "/images/icons/tag-white.svg"
    fontFamily: "Atkinson Hyperlegible"

  # navbar options
  navbar:
    fontFamily: "Atkinson Hyperlegible"
    showIcons: False
    
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    # the starting folder is configure in "assetDir" of this file
    image: "/images/error_404.png"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 929px

  # homepage options
  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be: "none", "menu", "footer" or "menu+footer"
    linkPosition: "menu+footer" 
    # this options let you specify the text of the link to the homepage
    linkText: "Strona główna"
    # option to specify the title in the homepage
    title: Bartosz Szafarz
    # option to specify the subtitle in the homepage
    subtitle: Witaj na mojej stronie
    # option to specify image in the homepage
    image: "/images/avataaars.png" # worker.svg 
    # option to specify the width of the image in the homepage
    imageWidth: 528px

  # footer options
  footer:
    # option to specify the logo in the footer
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/my_logo-big.png"
    email: 
      link: szafarz.bartosz@gmail.com
      title: szafarz.bartosz@gmail.com
    linkedin: 
      link: in/bszafarz
      title: in/bszafarz
    # facebook: 
    #   link: your.username
    #   title: Facebook
    github: 
      link: bszafarz
      title: bszafarz
    # twitter: 
    #    link: username
    #    title: Twitter
    instagram: 
      link: szafarz.bartosz
      title: szafarz.bartosz
    # telegram: 
    #    link: username
    #    title: Telegram
    copyright: Bartosz Szafarz - 2022

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  pl:
    languageName:       Polish
    weight:             1
  en:
    languageName:       English
    weight:             2
    params:
      homepage:
        title: Bartosz Szafarz
        subtitle: Welcome on my personal website
        linkPosition: "menu+footer"
        linkText: "Home"
        image: "/images/avataaars.png" # worker.svg 
        imageWidth: 528px
      
      footer:
        logo: "/images/my_logo-big.png"
        email: 
          link: szafarz.bartosz@gmail.com
          title: szafarz.bartosz@gmail.com
        linkedin: 
          link: in/bszafarz
          title: in/bszafarz
        # facebook: 
        #   link: your.username
        #   title: Facebook 
        # twitter: 
        #   link: username
        #   title: Twitter
        instagram: 
          link: szafarz.bartosz
          title: szafarz.bartosz
        github: 
          link: bszafarz
          title: bszafarz
        copyright: Bartosz Szafarz - 2022
      
